#ifndef START_PINS_H_
#define START_PINS_H_

#include <hal_gpio.h>

/* SAME54 has 14 pin functions */
#define GPIO_PIN_FUNCTION_A 0
#define GPIO_PIN_FUNCTION_B 1
#define GPIO_PIN_FUNCTION_C 2
#define GPIO_PIN_FUNCTION_D 3
#define GPIO_PIN_FUNCTION_E 4
#define GPIO_PIN_FUNCTION_F 5
#define GPIO_PIN_FUNCTION_G 6
#define GPIO_PIN_FUNCTION_H 7
#define GPIO_PIN_FUNCTION_I 8
#define GPIO_PIN_FUNCTION_J 9
#define GPIO_PIN_FUNCTION_K 10
#define GPIO_PIN_FUNCTION_L 11
#define GPIO_PIN_FUNCTION_M 12
#define GPIO_PIN_FUNCTION_N 13

/* STDIO_REDIRECT */
#define PB24 GPIO(GPIO_PORTB, 24)
#define PB25 GPIO(GPIO_PORTB, 25)

/* LIDAR */
#define PA04 GPIO(GPIO_PORTA, 4) /* USART : Tx */
#define PA05 GPIO(GPIO_PORTA, 5) /* USART : Rx */
#define PB09 GPIO(GPIO_PORTB, 9) /* PWM : WO/1 */

/* SERVO */
#define PA07 GPIO(GPIO_PORTA, 7) /* PWM : WO/1 */

/* SDMMC */
#define PA20 GPIO(GPIO_PORTA, 20) /* SDCMD   */
#define PA21 GPIO(GPIO_PORTA, 21) /* SDCK    */
#define PB18 GPIO(GPIO_PORTB, 18) /* SDDAT/0 */
#define PB19 GPIO(GPIO_PORTB, 19) /* SDDAT/1 */
#define PB20 GPIO(GPIO_PORTB, 20) /* SDDAT/2 */
#define PB21 GPIO(GPIO_PORTB, 21) /* SDDAT/3 */
#define CARD_DETECT_0 GPIO(GPIO_PORTD, 20)
#define WRITE_PROTECT_0 GPIO(GPIO_PORTD, 21)

/* GPIO */
#define START_BTN GPIO(GPIO_PORTA, 27)
#define LED_STATUS GPIO(GPIO_PORTA, 6)
#define LED0 GPIO(GPIO_PORTC, 18)

#endif // START_PINS_H_
